-- ============================================================
-- SCALABLE SUMMIT CRM — Supabase Schema
-- Run this entire file in Supabase > SQL Editor > New Query
-- ============================================================

-- 1. POSTS TABLE
create table if not exists public.posts (
  id            serial primary key,
  first_name    text not null,
  last_name     text,
  title         text,
  company       text,
  post_link     text,
  summary       text,
  tagged        text,
  reactions     integer default 0,
  comments      integer default 0,
  reposts       integer default 0,
  user_email    text,          -- email of the person who "owns" this row
  user_id       uuid,          -- linked to auth.users once they register
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- 2. ROW LEVEL SECURITY
alter table public.posts enable row level security;

-- Admin can do everything (set your email below)
create policy "Admin full access" on public.posts
  for all
  using (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@EMAIL.COM')
  with check (auth.jwt() ->> 'email' = 'YOUR_ADMIN_EMAIL@EMAIL.COM');

-- Users can read their own row
create policy "Users read own row" on public.posts
  for select
  using (auth.jwt() ->> 'email' = user_email);

-- Users can update their own row
create policy "Users update own row" on public.posts
  for update
  using (auth.jwt() ->> 'email' = user_email)
  with check (auth.jwt() ->> 'email' = user_email);

-- 3. AUTO-UPDATE updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_post_updated
  before update on public.posts
  for each row execute procedure public.handle_updated_at();

-- 4. SEED DATA — all 56 posts
insert into public.posts (first_name, last_name, title, company, post_link, summary, tagged, reactions, comments, reposts, user_email) values
('James', 'Creech', 'Founder & CEO', 'Quartermast Advisors', 'https://www.linkedin.com/posts/jlcreech_highlights-from-the-inaugural-scalable-summit-activity-7458168832491302912-VIH0', 'James shares 4 highlights from the inaugural Scalable Summit: (1) Praised hosts Kaya Yurieff and Jasmine Enberg for a great crowd, terrific speakers, and fascinating conversations. (2) Highlighted strong networking opportunities throughout the day. (3) Complimented The Lighthouse as an awesome venue. (4) Noted the industry is maturing with emerging opportunities in creator marketing, social commerce, and creator-led business investing.', 'Kaya Yurieff, Jasmine Enberg, The Lighthouse, Scalable Pod', 155, 16, 3, 'james@quartermast.com'),
('Kaya', 'Yurieff', 'Co-Founder & Co-CEO', 'Scalable', 'https://www.linkedin.com/posts/kayayurieff_wow-when-we-left-our-jobs-last-year-and-share-7458529466521251841-55_K', 'Kaya reflects on the overwhelming success of the first Scalable Summit, which drew over 400 attendees — standing room only. Thanks title sponsor Agentio and premier partners. Shouts out The Lighthouse as venue partner and the entire team.', 'Agentio, Arthur Leopold, Motion Society, Creative Artists Agency, Greenberg Glusker LLP, Core Advisors, Whalar Group, Fathers Beer, The Lighthouse, Neil Waller, Jon Goss, Courtney Kaczak Bartholomew, Michelle Curtis, Brent Weinstein, Jacob Selzer, Jasmine Enberg', 333, 53, 4, 'kaya@scalablepod.com'),
('Chris', 'Landa', 'Founder', 'Independent / Creator Economy Consultant', 'https://www.linkedin.com/posts/chris-landa-5297a79_what-can-i-write-about-the-scalable-summit-activity-7458562310417063936-I1lK', 'Chris shares 5 unique takeaways from the Scalable Summit including the CAA 4D chess lanyard strategy, the room diversity, venue vibes, VidCon vs Cannes debate, and excitement around AI curiosity.', 'Creative Artists Agency, Greg Goodfried, VidSummit, Ben Relles, Monica Khan, Soham H Patel, Andy Stack, Youran Cai, The Creator Society, VidCon, Cannes Lions International Festival of Creativity, Scalable Pod, Lauren Schnipper', 53, 14, 3, NULL),
('Stacy', 'Martinet', 'CMO & Chief Communications and Creative Officer', 'Adobe', 'https://www.linkedin.com/posts/stacymgreen_creativityatscale-influencermarketing-creatoreconomy-ugcPost-7458921403376017408-Neut', 'Stacy reflects on a panel she participated in at the Scalable Summit alongside Frank Cooper III and Arthur Leopold, moderated by Jasmine Enberg. Her central theme: the most effective creator strategies today are relationship-driven, not transactional.', 'Frank Cooper III, Visa, Arthur Leopold, Agentio, Jasmine Enberg, Kaya Yurieff, Jamie Gutfreund', 83, 8, 4, NULL),
('Yury', 'Adamov', 'Director, Global Corporate Strategy', 'Warner Bros. Discovery', 'https://www.linkedin.com/posts/yury-adamov-aa417428_scalablesummit-ugcPost-7458921362254925826-LGF-', 'Yury shares 5 reflections from the inaugural Scalable Summit on live content, creator partnerships, creator finance gaps, media fragmentation, and the Hollywood/Creator Economy convergence.', 'Scalable Pod', 50, 6, 1, NULL),
('Social Commerce', 'News', 'Company Page', 'Social Commerce News', 'https://www.linkedin.com/posts/socialcommercenews_socialcommercesummit-scalablesummit-socialcommercesummit-activity-7458550300237414400-Zs_i', 'Social Commerce News shares that their team stepped out of planning mode to attend the Scalable Summit in Los Angeles for inspiration.', 'Social Commerce News, Scalable Pod, Kaya Yurieff, Jasmine Enberg', 27, 4, 4, NULL),
('Theresa', 'Go', 'VP Responsible Media Solutions', 'Pixability', 'https://www.linkedin.com/posts/theresa-go-31015828_thank-you-jasmine-enberg-and-kaya-yurieff-activity-7458548455032901632-MYW2', 'Theresa thanks Jasmine Enberg and Kaya Yurieff for a fun, smart, and thought-provoking Scalable Summit 2026. Describes the panels in three words: Clips, Microdramas, and AI-eye-roll.', 'Jasmine Enberg, Kaya Yurieff, Jamie Gutfreund, Joshua Cohen, Evan Britton, Zoe Soon', 35, 2, 1, NULL),
('Joshua', 'Schmiesing', 'Marketing, Growth & Platform Strategy', 'Stagwell', 'https://www.linkedin.com/posts/schmiesing_were-going-to-have-a-creative-renaissance-activity-7458257763379589121-CECK', 'Joshua opens with a quote from Stacy Martinet of Adobe: We''re going to have a creative renaissance... because it''s going to force us to think about what makes the human contribution special.', 'Stacy Martinet, Adobe, Scalable Pod', 52, 4, 1, NULL),
('Lauren', 'Schnipper', 'Digital Media Executive | Creator Upload Co-host', 'Creator Upload', 'https://www.linkedin.com/posts/schnipper_yesterday-was-the-first-scalable-summit-in-activity-7458166265023668224-SN_y', 'Lauren humorously writes about missing the first Scalable Summit in LA due to prior obligations, despite serious FOMO.', 'Zach Blume, Kudzi Chikumbu, Joshua Cohen, Kaya Yurieff, Jasmine Enberg, Michelle Curtis, Jamie Gutfreund, Saurabh Shah, Chris Landa, Adam Wescott', 104, 17, 1, NULL),
('John', 'McCarus', 'Executive Recruiter, Advisor & Coach', 'Content Ink', 'https://www.linkedin.com/posts/johnmccarus_scalablesummit2026-activity-7457840830502834176-hk2G', 'John congratulates Kaya Yurieff and Jasmine Enberg on kicking off the first Scalable Summit, complimenting them on looking fabulous as well.', 'Kaya Yurieff, Jasmine Enberg', 60, 4, 3, NULL),
('Adam J.', 'Fowler', 'Economic Development | Creative Economy | Labor Market Economics', 'CVL Economics', 'https://www.linkedin.com/posts/adamjamesfowler_great-morning-with-the-cvl-economics-team-activity-7457888510621065216-Liwk', 'Adam shares a morning at the Scalable Pod Summit at The Lighthouse Venice with the CVL Economics team attending the Future of Entertainment panel.', 'CVL Economics, Scalable Pod, The Lighthouse, Kaya Yurieff, Jasmine Enberg', 26, 0, 1, NULL),
('Gabriela', 'Gironas', 'Creator Economy & Cultural Strategy Leader | Senior Director', 'The Team', 'https://www.linkedin.com/posts/gabrielagironas_had-such-a-stellar-time-at-scalable-summit-activity-7457973232017776640-FXhO', 'Gabriela shares that she had a stellar time at the Scalable Summit, giving a big shoutout to Kaya Yurieff and Jasmine Enberg for the incredibly curated panels and attendees.', 'Kaya Yurieff, Jasmine Enberg, Scalable Pod', 46, 0, 1, NULL),
('Scalable', 'Pod', 'Company Page', 'Scalable Pod', 'https://www.linkedin.com/posts/scalable-pod_were-still-buzzing-from-our-first-scalable-activity-7458646126452289536-xkFz', 'Scalable Pod''s official post-event recap celebrating the first Scalable Summit with 400+ attendees. Thanks all sponsors and partners.', 'Agentio, Motion Society, Creative Artists Agency, Greenberg Glusker LLP, ElevenLabs, Core Advisors, Whalar Group, Fathers Beer, Neil Waller, Jon Goss, Courtney Kaczak Bartholomew, Michelle Curtis, Brent Weinstein, Jacob Selzer, The Lighthouse', 115, 8, 2, NULL),
('Youran', 'Cai', 'Digital Marketer for Emerging Brands | Graphic Designer', 'The Creator Society', 'https://www.linkedin.com/posts/youran-cai_what-a-blast-at-scalable-summit-yesterday-ugcPost-7458301383130390528-2uGD', 'Youran reflects on attending the Scalable Summit for the first time as part of The Creator Society — describing it as both intimidating and exhilarating.', 'The Creator Society, Marisa Hammonds, Frank Cooper III, Nila Makhfi M.S., Carina Williamson, Larry Shapiro, Kaya Yurieff, Jasmine Enberg', 29, 4, 1, NULL),
('Underscore Talent', 'Management', 'Company Page', 'Underscore Talent Management', 'https://www.linkedin.com/posts/underscoretalent_scalablesummit-talentmanagement-creatoreconomy-ugcPost-7458622126191726594-w4Qt', 'Underscore Talent Management celebrates the first-ever Scalable Pod Summit, highlighting their client Joanne Molinaro on the Scaling Social Commerce panel.', 'Scalable Pod, Kaya Yurieff, Jasmine Enberg, Joanne Molinaro, Olivia Owens, Lauren Glaubach, Lia Haberman, Reza Izad, Dan Weinstein, Nick Jacklin, Shorthand Studios', 15, 1, 1, NULL),
('Johana', 'Gutierrez', 'Marketing', 'Loti AI', 'https://www.linkedin.com/posts/johana-s-gutierrez_this-week-i-had-the-opportunity-to-attend-ugcPost-7458639320690630656-IQDn', 'Johana reflects on attending her first Scalable Summit, describing it as a genuinely great experience with uplifting energy.', 'Loti AI, Kaya Yurieff, Jasmine Enberg', 20, 1, 1, NULL),
('April M.', 'Paredes', 'Attorney for Driven Entrepreneurs and Creators', 'Ascent Legal', 'https://www.linkedin.com/posts/aprilparedes_scalablesummit-creatoreconomy-innovation-ugcPost-7458647931731034112-jGj3', 'April attended the first Scalable Summit and came away genuinely impressed, focused on what''s actually happening now in the creator economy.', 'Ascent Legal, Kaya Yurieff, Jasmine Enberg', 39, 2, 2, NULL),
('Loti', '', 'Company Page', 'Loti AI', 'https://www.linkedin.com/posts/goloti_lotiai-scalablesummit-creatoreconomy-ugcPost-7458621457070215168-kXFl', 'Loti reflects on Scalable Summit 2026, noting conversations kept circling back to one theme: control.', 'Loti, Kaya Yurieff, Jasmine Enberg', 17, 0, 1, NULL),
('Ilia', 'Sky', 'Co-Founder & CEO', 'Mediator', 'https://www.linkedin.com/posts/ilia-sky_scalable-summit-on-wednesday-was-excellent-ugcPost-7458597739308765184-a3xI', 'Ilia calls the Scalable Summit excellent, noting the between-panel conversations were even better than the panels themselves.', 'Kaya Yurieff', 10, 1, 1, NULL),
('Catherine', 'Browne', 'Vice President', 'The Roost Podcast Network', 'https://www.linkedin.com/posts/catherine-browne_scalable-summit-was-the-creator-industry-ugcPost-7458556380971433984-0SYQ', 'Catherine shares key takeaways from the first ever Scalable Pod Summit, featuring video interviews with three industry leaders.', 'Scalable Pod, Jeremy Lermitte, Grant Derkac, Mary Grace Scully, Kaya Yurieff, Jasmine Enberg', 53, 7, 3, NULL),
('Jean-Loup', 'Fraudin', 'Co-Founder', 'Motion Society', 'https://www.linkedin.com/posts/jean-loup-fraudin-594594a8_scalablesummit-creatoreconomy-motionsociety-ugcPost-7458552127775297536-2J02', 'Jean-Loup expresses pride that Motion Society got to support the first Scalable Summit in LA.', 'Motion Society, Kaya Yurieff, Jasmine Enberg, Scalable Pod', 39, 1, 3, NULL),
('Peter', 'Nordahl-Hansen', 'Digital Media Executive, Consultant, Producer', 'N/A', 'https://www.linkedin.com/posts/penoha_was-the-scalable-pod-summit-worth-it-in-ugcPost-7458292221344243712-IYAD', 'Peter answers his own question — was the Scalable Pod Summit worth it? Absolutely.', 'Scalable Pod, Rich Bloom, Ian Schafer, Nishat K., Jordan Newman, Kaya Yurieff, Jasmine Enberg', 37, 2, 1, NULL),
('Jennifer', 'Piña', 'Co-Founder', 'MagicLinks', 'https://www.linkedin.com/posts/jenpina_fun-one-yesterday-at-scalable-pod-summit-ugcPost-7458248407371968512-byzj', 'Jennifer shares highlights from the Scalable Pod Summit. Favorite session: Kaya interviewing David Duxin from OpenAI about how creator content shows up in AI search.', 'Scalable Pod, Kaya Yurieff, Jasmine Enberg, MagicLinks, The Lighthouse, David Duxin', 75, 7, 2, NULL),
('Uptin', 'S', 'Tech & Money Creator | Exited Founder', 'Independent Creator', 'https://www.linkedin.com/posts/uptin_just-finished-attending-an-epic-inaugural-ugcPost-7458282691470278656-tZPx', 'Uptin shares a brief but enthusiastic recap of attending Scalable Summit 2026 at The Lighthouse.', 'The Lighthouse, Kaya Yurieff, Jasmine Enberg', 36, 0, 2, NULL),
('Rebecca', 'Plotkin', 'Creators', 'LinkedIn', 'https://www.linkedin.com/posts/rebecca-plotkin-29479745_some-common-themes-popped-up-across-the-speakers-ugcPost-7458370303346335744-bixK', 'Rebecca shares common themes from the Scalable Summit speakers: creators break through by staying niche.', 'Adobe, Visa, Kaya Yurieff, Jasmine Enberg, Lucy Quick', 57, 14, 2, NULL),
('William', 'Muno', 'Partnerships', 'Agentio', 'https://www.linkedin.com/posts/william-muno-913524bb_what-a-week-in-la-agentio-was-proud-to-ugcPost-7458542410483027968-3cMr', 'William celebrates Agentio''s role as title partner of the first-ever Scalable Pod Summit.', 'Agentio, Scalable Pod, Kaya Yurieff, Jasmine Enberg, Arthur Leopold, Monica Khan, Jamie Gutfreund', 76, 14, 3, NULL),
('Hanna', 'Simonson', 'Founder & CEO', 'NOORI', 'https://www.linkedin.com/posts/hstalent_great-spending-time-with-familiar-faces-and-ugcPost-7458210456319672320-KBTs', 'Hanna enjoyed connecting with familiar faces and new friends at the Scalable Pod Summit. Biggest takeaway: impact is now hyper-accelerated.', 'Scalable Pod, The Publish Press', 46, 6, 1, NULL),
('Ashley', 'Falls', 'Managing Director', 'The Clios', 'https://www.linkedin.com/posts/ashley-falls-97156774_yesterday-i-attended-the-scalable-summit-ugcPost-7458210594064809984-yWvn', 'Ashley attended the Scalable Summit at The Lighthouse Campus in Venice and was blown away as a frequent conference-goer.', 'The Lighthouse, Scalable Pod', 29, 5, 2, NULL),
('Abbie', 'Sheppard', 'Creators', 'Agentio', 'https://www.linkedin.com/posts/abbiesheppard_all-in-the-first-week-of-may-1-we-sent-ugcPost-7458212184410619904-bqJ0', 'Abbie recaps a packed first week of May for Agentio, including title sponsorship of the Scalable Pod Summit.', 'Agentio, Jared Read, Riley Tanabe, Scalable Pod, Kaya Yurieff, Jasmine Enberg, Arthur Leopold', 93, 13, 3, NULL),
('Neil', 'Waller', 'Co-Founder', 'Whalar Group / The Lighthouse', 'https://www.linkedin.com/posts/neil-waller_yesterday-we-hosted-the-inaugural-scalable-ugcPost-7458203808129654784-mgMY', 'Neil reflects on co-hosting the inaugural Scalable Pod Summit at The Lighthouse, expressing awe at what Kaya Yurieff and Jasmine Enberg built.', 'Scalable Pod, The Lighthouse, Kaya Yurieff, Jasmine Enberg, Courtney Kaczak Bartholomew, Michelle Curtis, Liza Herlands', 195, 63, 3, NULL),
('Thomas', 'Subra', 'Co-Founder', 'Motion Society', 'https://www.linkedin.com/posts/thomas-subra-7939baa7_was-at-a-small-dinner-with-daniel-clancy-ugcPost-7458271854877667328-Vhvw', 'Thomas shares a key insight from a pre-summit dinner with Twitch CEO Daniel Clancy: Being everywhere is a game of top of mind.', 'Daniel Clancy, Scalable Pod, Motion Society, Kaya Yurieff, Jasmine Enberg, Whalar, The Lighthouse', 36, 0, 3, NULL),
('Alice', 'Chan', 'Strategist, Marketing & Comms C-Level Leader', 'N/A', 'https://www.linkedin.com/posts/alicechan_a-stellar-day-at-the-scalable-summit-huge-ugcPost-7457994160604704769-xVQO', 'Alice calls the Scalable Summit a stellar day, giving huge kudos to Kaya Yurieff and Jasmine Enberg.', 'Kaya Yurieff, Jasmine Enberg, Jim Louderback, Emily McDonnell', 30, 2, 2, NULL),
('Mike', 'Duffy', 'Emmy-winning Show Creator', 'N/A', 'https://www.linkedin.com/posts/mike-duffy-3b70197_scalable-creator-ugcPost-7457919154277355520-rTuW', 'Mike highlights a key insight: brands allocating 12-18 months of budget to YouTube content are reaping the benefits.', 'Kaya Yurieff, Jasmine Enberg, Neil Waller, Jason Y. Lee, Michelle Beaver, Matt Gielen, Zach Hirsch, Alex Barinka', 40, 3, 3, NULL),
('Robb', 'Montgomery', 'Founder, Author, Educator, Filmmaker', 'Smart Film School', 'https://www.linkedin.com/posts/robbmontgomery_scalablesummit-creatoreconomy-trustgraph-ugcPost-7457838563691220992-SNT4', 'Robb shares a fun, brief post about biking from Hollywood to Venice to attend the sold-out Scalable Summit.', 'Kaya Yurieff, Jasmine Enberg', 8, 0, 1, NULL),
('Espree', 'Devora', 'Artist of Human Connection | SXSW Startup', 'N/A', 'https://www.linkedin.com/posts/espree_creatoreconomy-scalablesummit-media-ugcPost-7457862141312880641-HJOh', 'Espree shares real-time energy from the Scalable Summit. Central theme: brands need to become media companies.', 'The Lighthouse, Jasmine Enberg, Kaya Yurieff, Scalable Pod, Whalar Group', 56, 10, 3, NULL),
('Open', 'Influence', 'Company Page', 'Open Influence', 'https://www.linkedin.com/posts/openinfluence_scalablesummit2026-creatoreconomy-monoculture-ugcPost-7457905751257190400-ni43', 'Open highlights one of the most compelling conversations: monoculture is dead.', 'Rich Bloom, Tubi, Ian Schafer, Ensemble, Amanda McCants, Scalable Pod, Jasmine Enberg', 14, 3, 2, NULL),
('Maria A.', 'Rodriguez', 'Marketing and Communications Leader', 'Open Influence', 'https://www.linkedin.com/posts/mariarodriguezh_scalablesummit2026-creatoreconomy-tiktok-ugcPost-7457893402005757952-Ys1L', 'Maria shares live coverage from the Scalable Summit, highlighting a conversation between Marisa Hammonds and Jasmine Enberg.', 'Marisa Hammonds, TikTok, Jasmine Enberg, Scalable Pod, Open Influence', 11, 0, 2, NULL),
('Lia', 'Haberman', 'Creator Economy Expert | Advisor | Educator', 'ICYMI Newsletter', 'https://www.linkedin.com/posts/liahaberman_are-you-ready-for-instagrams-return-to-long-form-ugcPost-7458516944661458944-5zA_', 'Lia shares one of the most detailed recaps, leading with a big takeaway: Instagram''s return to long-form content.', 'Lauren Glaubach, Olivia Owens, Joanne Molinaro, Kaya Yurieff', 62, 19, 3, NULL),
('Jasmine', 'Enberg', 'Co-Founder & Co-CEO', 'Scalable', 'https://www.linkedin.com/posts/jasmine-enberg_wow-we-are-so-blown-away-by-the-energy-activity-7458521210490880002-mkCi', 'Jasmine shares a heartfelt post-event recap of the first-ever Scalable Summit, expressing awe at the energy, enthusiasm and insights from attendees.', 'Jon Goss, Agentio, Motion Society, Creative Artists Agency, Whalar Group, ElevenLabs, The Lighthouse, Neil Waller, Courtney Kaczak Bartholomew, Michelle Curtis, Brent Weinstein, Jacob Selzer, Kaya Yurieff', 227, 19, 2, NULL),
('Ian', 'Schafer', 'Co-Founder & President', 'Ensemble (HOORAE Media)', 'https://www.linkedin.com/posts/ianschafer_scalable-pods-first-summit-was-a-fantastic-ugcPost-7458265712361422849-Fxrj', 'Ian calls the Scalable Pod Summit a fantastic experience, praising the insightful, provocative, and deep programming.', 'Scalable Pod, The Lighthouse, Kaya Yurieff, Jasmine Enberg, Michelle Curtis, Zach Blume, Frank Cooper III, Stacy Martinet, Marisa Hammonds, Jamie Gutfreund, Rich Bloom, Neil Waller', 74, 12, 2, NULL),
('Makayla', 'Denninger', 'Partnerships & Business Development Lead', 'N/A', 'https://www.linkedin.com/posts/makayla-denninger-301073135_scalablesummit2026-ugcPost-7458022135924547584-kqZG', 'Makayla shares her first-time experience at Scalable Summit 2026 with 4 key takeaways.', 'Scalable Pod, Kaya Yurieff, Jasmine Enberg, Rich Bloom, Robert Santini, Frank Cooper III, Lauren Glaubach, Olivia Owens, Joanne Molinaro, Stacy Martinet', 21, 0, 1, NULL),
('Lexi', 'St. John', 'Co-Founder & President', 'The Nod Collective', 'https://www.linkedin.com/posts/lexistjohn_absolutely-blown-away-by-yesterdays-inaugural-ugcPost-7458256866834526208-NHyb', 'Lexi was blown away by the inaugural Scalable Summit. Says this one felt different — smarter, more strategic, professionalized.', 'The Lighthouse, Kaya Yurieff, Jasmine Enberg, Scalable Pod, Daniel Clancy, David Duxin, Marisa Hammonds, Frank Cooper III', 25, 3, 1, NULL),
('Anna', 'Blore', 'Global Creator Programs Lead, TV & Film', 'N/A', 'https://www.linkedin.com/posts/activity-7458759925566115843-3Iw5', 'Anna shares a concise key takeaway: the creator economy is moving beyond follower count toward cultivating die-hard fandoms.', 'Aisha Shah', 7, 1, 0, NULL),
('Robert', 'True', 'Executive Producer & Senior Content Strategist', 'Visa', 'https://www.linkedin.com/posts/itsroberttrue_scalablesummit-creatoreconomy-marketing-activity-7458140566527336448-00CH', 'Robert shares 5 platform-organized takeaways centered on: trust is becoming more valuable than reach.', 'The Lighthouse, Twitch, Daniel Clancy, TikTok, Spotify, Vox, Tubi, Ensemble, Frank Cooper III', 10, 4, 0, NULL),
('Maria A.', 'Rodriguez', 'Marketing and Communications Leader', 'Open Influence', 'https://www.linkedin.com/posts/mariarodriguezh_scalablesummit-creatoreconomy-socialcommerce-activity-7458219183974166529-yGQj', 'Maria shares a second post focusing on: The funnel is collapsing into the feed.', 'Lia Haberman, Lauren Glaubach, Scalable Pod, Jasmine Enberg, Kaya Yurieff', 2, 0, 0, NULL),
('Jim', 'Louderback', 'Editor & CEO', 'Inside the Creator Economy', 'https://www.linkedin.com/posts/jlouderb_daniel-clancy-thinks-nobody-met-their-partner-activity-7458197698815348737-6JIU', 'Jim delivers one of the most detailed and editorial recaps of the Scalable Summit.', 'Daniel Clancy, Marisa Hammonds, Ian Schafer, Rich Bloom, Amanda McCants, David Duxin, Kaya Yurieff, Jasmine Enberg', 82, 21, 0, NULL),
('David', 'Brinker', 'Multifaceted Tech, Media & Music Sector Executive', 'N/A', 'https://www.linkedin.com/posts/davidbrinker_one-of-the-luckiest-aspects-of-my-career-activity-7458311235441213440-pY3a', 'David shares a heartfelt post framing the event as a testament to Kaya and Jasmine''s ambition and Neil Waller''s vision for The Lighthouse.', 'Kaya Yurieff, Jasmine Enberg, Neil Waller', 65, 4, 0, NULL),
('Damiano', 'Crognali', 'Journalist | Podcast Pioneer | Expert in AI', 'TIM AI Voices', 'https://www.linkedin.com/posts/damianocrognali_creatoreconomy-intelligenzaartificiale-scalablesummit-activity-7458459982032748544-TdpU', 'Damiano frames the Scalable Summit as one of the most relevant events at the intersection of AI and the influencer industry.', 'Kaya Yurieff', 5, 1, 2, NULL),
('Dylan', 'Huey', 'Gen Z Founder, TedX Speaker, Digital Creator & Musician', 'N/A', 'https://www.linkedin.com/posts/dylanhuey40_yes-i-did-make-it-out-to-scalable-pod-summit-activity-7458168822919880704-TLM2', 'Dylan confirms his attendance at the Scalable Pod Summit with a short, playful post.', 'Scalable Pod, Jasmine Enberg, Kaya Yurieff', 18, 1, 0, NULL),
('At The Moment', 'Media (ATM)', 'Company Page', 'At The Moment Media', 'https://www.linkedin.com/posts/atm-media-at-the-moment-media_atm-advertising-technology-activity-7458183870908268544-hGZE', 'At The Moment Media recaps attending two invite-only LA industry events that both told the same story: creators and human-centered stories are the secret to scale.', 'Matthew Belloni, Puck, Jasmine Enberg, Kaya Yurieff, Scalable Pod', 11, 2, 2, NULL),
('Meredith', 'Prunkard', 'VP, Original Productions', 'N/A', 'https://www.linkedin.com/posts/meredith-prunkard-91b0736_scalable-activity-7458331691380678656-bm6-', 'Meredith shares her enthusiasm for the Scalable Summit, calling it a valuable and inspiring day.', 'Sara Hoerner, Michaela Hammond, Monica Khan, Jasmine Enberg, Kaya Yurieff', 19, 1, 1, NULL),
('Nila', 'Makhfi', 'Founder | IRL Events for LinkedIn Creators', 'Parkzy', 'https://www.linkedin.com/posts/nilamakhfi_the-creator-economy-is-no-longer-the-future-activity-7458191425965506560-PIbx', 'Nila opens with: The creator economy is no longer the future — it''s already shaping business, media, and consumer behavior in real time.', 'Lia Haberman, Lauren Glaubach, Joanne Molinaro, Olivia Owens, Kaya Yurieff, Jasmine Enberg', 77, 21, 1, NULL),
('Kayla', 'Jeter', 'Founder, Coach, Athlete, Mental Health Advocate, Creator', 'N/A', 'https://www.linkedin.com/posts/kayla-jeter_scalablesummit2026-thelighthousecampus-mentalhealthmonth-activity-7458459447808532482-ODt7', 'Kayla shares a deeply personal reflection on attending the Scalable Summit during Mental Health Awareness Month.', 'The Lighthouse, Kaya Yurieff, Jasmine Enberg, Scalable Pod, Daniel Clancy, Michelle Beaver, Tessa Lyons, Arthur Leopold, Frank Cooper III, Stacy Martinet', 18, 2, 0, NULL),
('Mark', 'Sarsha', 'Founder/Head of Brand and Entertainment Partnerships', 'N/A', 'https://www.linkedin.com/posts/marksarsha_so-great-to-catch-up-with-the-fabulous-jo-activity-7457934434844082176-NmWZ', 'Mark shares a photo from the Scalable Summit backdrop with Jo Cronk, Co-CEO of Whalar.', 'Jo Cronk', 46, 1, 0, NULL),
('Guillaume', 'de Chalendar', 'EVP Media & Entertainment Banking | Strategic Financing', 'Banc of California', 'https://www.linkedin.com/posts/guillaume-de-chalendar', 'Guillaume shares a post from the Scalable Summit asking how to win on YouTube, which owns 30% of all TV consumption.', 'YouTube, Banc of California', 8, 0, 0, NULL),
('Monica', 'Khan', 'Creator-Led Growth Strategist', 'N/A', 'https://www.linkedin.com/posts/monica-khan-creator-led-growth', 'Monica writes one of the most analytical posts, drawing a parallel between OpenAI acquiring TBPN and The Lighthouse launching Scalable as a 50-50 joint venture. Her thesis: Neither company is buying content. They''re buying proximity to the people shaping the conversation.', 'The Lighthouse, Kaya Yurieff, Jasmine Enberg, Whalar Group, Neil Waller, Jon Goss, Jo Cronk', 172, 41, 1, NULL);
