import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabaseClient'

export default function Reports() {
  const [user, setUser] = useState(null)

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) setUser(session.user)
    })
  }, [])

  const reports = [
    {
      title: 'Scalable Summit 2026',
      subtitle: 'LinkedIn Coverage Analysis',
      description: 'A comprehensive analysis of 57 LinkedIn posts generated by the inaugural Scalable Summit. Includes engagement leaderboards, posting frameworks, sponsor ROI breakdown, and strategic insights.',
      price: '$49',
      badge: 'Available Now',
      badgeColor: '#C8FF00',
      slug: 'scalable-summit-2026',
    },
  ]

  return (
    <div style={{ minHeight: '100vh', background: 'var(--navy)' }}>
      <header style={styles.header}>
        <a href="/" style={styles.logo}>
          <span style={{ color: 'var(--neon)', fontFamily: 'DM Serif Display, serif', fontStyle: 'italic' }}>Fruitful</span>
          <span style={{ fontFamily: 'DM Serif Display, serif' }}> Intelligence</span>
        </a>
        <nav style={styles.nav}>
          <a href="/" style={styles.navLink}>Events</a>
          <a href="/search" style={styles.navLink}>AI Search</a>
          <a href="/reports" style={{ ...styles.navLink, color: 'var(--neon)' }}>Reports</a>
        </nav>
        <div>
          {user
            ? <span style={{ fontSize: 12, color: 'var(--muted)' }}>{user.email}</span>
            : <a href="/login" style={styles.signInBtn}>Sign in</a>
          }
        </div>
      </header>

      <div style={{ maxWidth: 900, margin: '0 auto', padding: '60px 32px' }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 12, color: 'var(--neon)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: 12 }}>Research Reports</div>
          <h1 style={{ fontFamily: 'DM Serif Display, serif', fontSize: 48, fontStyle: 'italic', color: 'var(--white)', marginBottom: 12 }}>Event Intelligence Reports</h1>
          <p style={{ color: 'var(--muted)', fontSize: 16, maxWidth: 560, lineHeight: 1.6 }}>
            Deep-dive analysis of LinkedIn coverage from creator economy events. Data-driven insights for organizers, sponsors, and creators.
          </p>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
          {reports.map(r => (
            <div key={r.slug} style={styles.reportCard}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 24 }}>
                <div style={{ flex: 1 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}>
                    <span style={{ background: r.badgeColor, color: 'var(--navy)', fontSize: 10, fontWeight: 800, padding: '2px 8px', borderRadius: 4, textTransform: 'uppercase', letterSpacing: '1px' }}>{r.badge}</span>
                  </div>
                  <h2 style={{ fontFamily: 'DM Serif Display, serif', fontSize: 28, fontStyle: 'italic', color: 'var(--white)', marginBottom: 4 }}>{r.title}</h2>
                  <div style={{ fontSize: 14, color: 'var(--neon)', marginBottom: 12 }}>{r.subtitle}</div>
                  <p style={{ fontSize: 14, color: 'var(--muted)', lineHeight: 1.6, maxWidth: 500 }}>{r.description}</p>
                </div>
                <div style={{ textAlign: 'center', flexShrink: 0 }}>
                  <div style={{ fontFamily: 'DM Serif Display, serif', fontSize: 40, color: 'var(--neon)', marginBottom: 8 }}>{r.price}</div>
                  <a href={`https://fruitful.events/reports/${r.slug}`} target="_blank" rel="noreferrer"
                    style={{ display: 'block', background: 'var(--neon)', color: 'var(--navy)', fontWeight: 700, fontSize: 14, padding: '12px 28px', borderRadius: 8, whiteSpace: 'nowrap' }}>
                    Get Report →
                  </a>
                  <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 8 }}>One-time purchase</div>
                </div>
              </div>
            </div>
          ))}

          {/* Coming soon */}
          {['New Media Summit 2025', 'Newsletter Conference 2025', 'Craft & Commerce 2025'].map(name => (
            <div key={name} style={{ ...styles.reportCard, opacity: 0.5 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div>
                  <div style={{ background: 'var(--card2)', color: 'var(--muted)', fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 4, display: 'inline-block', marginBottom: 8, textTransform: 'uppercase', letterSpacing: '1px' }}>Coming Soon</div>
                  <h2 style={{ fontFamily: 'DM Serif Display, serif', fontSize: 24, fontStyle: 'italic', color: 'var(--white)' }}>{name}</h2>
                </div>
                <div style={{ fontSize: 13, color: 'var(--muted)' }}>Data being collected</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

const styles = {
  header: { background: 'rgba(11,22,40,0.95)', borderBottom: '1px solid rgba(200,255,0,0.1)', padding: '0 32px', height: 60, display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, zIndex: 100 },
  logo: { display: 'flex', alignItems: 'center', gap: 4, fontSize: 20, fontWeight: 600, textDecoration: 'none' },
  nav: { display: 'flex', gap: 28 },
  navLink: { color: 'var(--muted)', fontSize: 14, textDecoration: 'none' },
  signInBtn: { background: 'var(--neon)', color: 'var(--navy)', fontWeight: 700, fontSize: 12, padding: '7px 16px', borderRadius: 6 },
  reportCard: { background: 'var(--card)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: 12, padding: 28 },
}
